const socketEvents = {
  USER_DETAILS: "USER_DETAILS",
  CREATE_CHAT_ROOM: "CREATE_CHAT_ROOM",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CALL: "CALL",
  CALL_NOTIFICATION: "CALL_NOTIFICATION",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_READY: "CALL_READY",
  WEB_RTC_SIGNAL: "WEB_RTC_SIGNAL",
  NOTIFICATION: "NOTIFICATION",
};

export default socketEvents;
